name: Black Format Check

on:
  pull_request:

jobs:
  black-check:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment for Black
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install and run Black
      - name: Install Black
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Run Black check
        run: black --check .
