# This workflow will do a clean install of node dependencies, 
# build the source code and run tests across different versions of node
# For more information see: 
# https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3
      
    # Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.9.0'

    # Install dependencies (including Prettier and plugins)
    - name: Install dependencies
      working-directory: frontend
      run: npm install

    # Test build
    - name: Build
      working-directory: frontend
      run: npm run build --if-present
    #- run: npm test
