name: Prettier Format Check

on:
  pull_request:

jobs:
  prettier-check:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.9.0'

      # Install dependencies (including Prettier and plugins)
      - name: Install dependencies
        working-directory: frontend
        run: npm install

      # Run Prettier check
      - name: Run Prettier check
        working-directory: frontend
        run: npx prettier --check "**/*.{js,jsx,ts,tsx,html,css,json,md}"
