name: Python CI

on:
  pull_request:

jobs:
  py-backend-tests:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.0'

    # Install pytest and any required dependencies
    - name: Install dependencies
      working-directory: backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Run pytest
    - name: Run tests
      working-directory: backend
      run: pytest
